import { useContext } from "react"
import { Context } from './Context'

export const LangProvider = ({ location }) => {
    const { lang } = useContext(Context)

    const langObj = {
        "en": {
            "opening_heading": "Fast and reliable services for the best rates on the Internet!",
            "opening_p1": "Filing out immigration forms doesn’t have to be complicated or costly. Too often, lawyers charge excessive fees for straightforward paperwork, making the process unaffordable for many.",
            "opening_p2": "We believe everyone deserves access to affordable immigration support. We simplify the application process and ensure your forms are completed accurately and on time. With our help, you can confidently handle your immigration paperwork without the high price tag, giving you peace of mind and clarity on your journey forward!",
            "bp1": "Lowest rates",
            "bp2": "Fastest service",
            "bp3": "Quality guarantee",
            "services_heading": "Services",
            "basic": "Basic",
            "basic_txt": "We fill out the form and give you instructions on how to send it.",
            "premium": "Premium",
            "premium_txt": "We take care of everything! First class mailing fee is included in the price.",
            "family": "Family package",
            "family_txt": "All premium benefits for a reduced price if applying for at least 3 people.",
            "translation": "Translation",
            "translation_txt": "Certified translations of official documents like birth certificates, school diplomas, etc.",
            "translation_price": "15/page",
            "promo": "We value your referrals! Once you have purchased our services, you will earn a 40% commission on each successful referral. The individuals you refer will also receive a 10% discount on their first purchase.",
            "faq_heading": "FAQ",
            "q1": "Who are we?",
            "a1": "We are a small team of specialists who have firsthand experience with the American immigration system, which is why we understand the challenges facing most immigrants and the importance of affordability, accuracy and timeliness when dealing with immigration matters.",
            "q2": "How does this process work?",
            "a2": "Once you contact us using the form below, we will get in touch with you within 12 hours to gather some necessary information and answer any other questions you might have, after which we'll start working on your request.",
            "q3": "What if the application is not accepted?",
            "a3": "That has never happened before! But if for some reason your application gets sent back, we will retry at no additional cost to you or simply issue you a refund - whatever you prefer.",
            "q4": "Do you offer any other services?",
            "a4": "Yes! We offer different types of services to immigrants with language barriers and those who need help navigating different types of systems in the USA, such as healthcare, banking, education, etc.",
            "reviews_heading": "Reviews",
            "contact_heading": "Contact Us",
            "fname": "First name",
            "lname": "Last name",
            "email": "Email",
            "service": "Service",
            "ref_num": "Reference number (put 0 if none)",
            "service_num": "Service number",
            "service_num_incorrect": "Service number is incorrect",
            "choose_service": "Choose a service",
            "submit": "Submit",
            "sent": "Thank you for your message! We'll get in touch with you soon.",
            "error": "There was an unexpected error, please try again later."
        },
        "ru": {
    "opening_heading": "Быстрые и надежные услуги по лучшим ценам в Интернете!",
    "opening_p1": "Заполнение иммиграционных форм не обязательно должно быть сложным или дорогостоящим. Слишком часто юристы берут чрезмерные гонорары за простую бумажную работу, делая процесс недоступным для многих.",
    "opening_p2": "Мы считаем, что каждый заслуживает доступной иммиграционной поддержки. Мы упрощаем процесс подачи заявления и обеспечиваем точное и своевременное заполнение ваших форм. С нашей помощью вы можете уверенно справляться с иммиграционной документацией без высоких затрат, обрести спокойствие и ясность на пути вперед!",
    "bp1": "Самые низкие цены",
    "bp2": "Самый быстрый сервис",
    "bp3": "Гарантия качества",
    "services_heading": "Услуги",
    "basic": "Базовый",
    "basic_txt": "Мы заполняем форму и даем вам инструкции по ее отправке.",
    "premium": "Премиум",
    "premium_txt": "Мы берем все на себя! Плата за пересылку класса «первый» включена в стоимость.",
    "family": "Семейный пакет",
    "family_txt": "Все преимущества премиума по сниженной цене при подаче на минимум 3 человек.",
    "translation": "Перевод",
    "translation_txt": "Перевод официальных документов, таких как свидетельства о рождении, школьные дипломы и т. д.",
    "translation_price": "15/стр.",
    "promo": "Мы ценим ваши рекомендации! После покупки наших услуг вы получите комиссию в размере 40% за каждую успешную рекомендацию. Также рекомендованные вами лица получат скидку 10% на первую покупку.",
    "faq_heading": "Часто задаваемые вопросы",
    "q1": "Кто мы?",
    "a1": "Мы — небольшая команда специалистов, которые имеют собственный опыт работы с американской иммиграционной системой, поэтому мы понимаем трудности, с которыми сталкивается большинство иммигрантов, а также важность доступности, точности и своевременности в иммиграционных делах.",
    "q2": "Как работает этот процесс?",
    "a2": "После того, как вы свяжетесь с нами через форму ниже, мы свяжемся с вами в течение 12 часов, чтобы собрать необходимую информацию и ответить на любые ваши вопросы, после чего начнем работать над вашим запросом.",
    "q3": "Что делать, если заявление не будет принято?",
    "a3": "Этого никогда не происходило! Но если по какой-то причине ваше заявление будет возвращено, мы повторно отправим его бесплатно или просто вернем вам деньги — на ваш выбор.",
    "q4": "Вы предлагаете какие-либо другие услуги?",
    "a4": "Да! Мы предлагаем разные виды услуг для иммигрантов с языковыми барьерами и тех, кто нуждается в помощи с навигацией по разным системам в США, таким как здравоохранение, банки, образование и т. д.",
    "reviews_heading": "Отзывы",
    "contact_heading": "Свяжитесь с нами",
    "fname": "Имя",
    "lname": "Фамилия",
    "email": "Эл. почта",
    "service": "Услуга",
    "ref_num": "Номер ссылки (поставьте 0, если нет)",
    "service_num": "Номер услуги",
    "service_num_incorrect": "Номер услуги неверный",
    "choose_service": "Выберите услугу",
    "submit": "Отправить",
    "sent": "Спасибо за ваше сообщение! Мы скоро свяжемся с вами.",
    "error": "Произошла неожиданная ошибка, пожалуйста, попробуйте позже."
},
"tr": {
    "opening_heading": "İnternetin en iyi fiyatlarıyla hızlı ve güvenilir hizmetler!",
    "opening_p1": "Göçmenlik formlarını doldurmak karmaşık ya da pahalı olmak zorunda değil. Çok sık olarak avukatlar, basit işlemler için aşırı ücret talep ederek süreci birçok kişi için erişilemez hale getiriyor.",
    "opening_p2": "Herkesin uygun fiyatlı göçmenlik desteğine erişimi hak ettiğine inanıyoruz. Başvuru sürecini basitleştiriyor ve formlarınızın doğru ve zamanında doldurulmasını sağlıyoruz. Yardımımızla, yüksek maliyetler olmadan göçmenlik belgelerinizi güvenle doldurabilirsiniz; bu da size iç huzuru ve ileriye doğru netlik sağlar!",
    "bp1": "En düşük fiyatlar",
    "bp2": "En hızlı hizmet",
    "bp3": "Kalite garantisi",
    "services_heading": "Hizmetler",
    "basic": "Temel",
    "basic_txt": "Formu dolduruyor ve gönderim talimatları sağlıyoruz.",
    "premium": "Premium",
    "premium_txt": "Her şeyle ilgileniyoruz! Birinci sınıf posta ücreti fiyata dahildir.",
    "family": "Aile paketi",
    "family_txt": "En az 3 kişi başvurduğunda Premium avantajlarını indirimli fiyata sunuyoruz.",
    "translation": "Çeviri",
    "translation_txt": "Doğum sertifikaları, okul diplomaları gibi resmi belgelerin onaylı çevirileri.",
    "translation_price": "15/sayfa",
    "promo": "Tavsiyelerinize değer veriyoruz! Hizmetlerimizi satın aldıktan sonra, başarılı her yönlendirme için %40 komisyon kazanacaksınız. Tavsiye ettiğiniz kişiler ilk alışverişlerinde %10 indirim alacak.",
    "faq_heading": "SSS",
    "q1": "Biz kimiz?",
    "a1": "Amerikan göçmenlik sistemi konusunda ilk elden deneyime sahip küçük bir uzman ekibiyiz. Göçmenlik süreciyle ilgili zorlukları ve uygun fiyatlı, doğru, zamanında hizmetlerin önemini anlıyoruz.",
    "q2": "Bu süreç nasıl işler?",
    "a2": "Aşağıdaki form aracılığıyla bizimle iletişime geçtikten sonra, gerekli bilgileri toplamak ve sorularınızı yanıtlamak için 12 saat içinde sizinle iletişime geçeceğiz. Daha sonra isteğiniz üzerinde çalışmaya başlayacağız.",
    "q3": "Başvuru kabul edilmezse ne olur?",
    "a3": "Bu daha önce hiç olmadı! Ancak, herhangi bir nedenle başvurunuz geri dönerse, ek bir ücret ödemeden tekrar deneriz veya tercihinize göre ücretinizi iade ederiz.",
    "q4": "Başka hizmetler sunuyor musunuz?",
    "a4": "Evet! Dil engelleri yaşayan göçmenler ve ABD'deki sağlık, bankacılık, eğitim gibi çeşitli sistemlerde rehberliğe ihtiyaç duyanlar için çeşitli hizmetler sunuyoruz.",
    "reviews_heading": "Yorumlar",
    "contact_heading": "Bize Ulaşın",
    "fname": "Ad",
    "lname": "Soyad",
    "email": "E-posta",
    "service": "Hizmet",
    "ref_num": "Referans numarası (yoksa 0 yazın)",
    "service_num": "Hizmet numarası",
    "service_num_incorrect": "Hizmet numarası yanlış",
    "choose_service": "Bir hizmet seçin",
    "submit": "Gönder",
    "sent": "Mesajınız için teşekkür ederiz! Kısa süre içinde sizinle iletişime geçeceğiz.",
    "error": "Beklenmeyen bir hata oluştu, lütfen daha sonra tekrar deneyin."
},
"es": {
    "opening_heading": "¡Servicios rápidos y confiables a los mejores precios en Internet!",
    "opening_p1": "Completar formularios de inmigración no tiene que ser complicado o costoso. Con demasiada frecuencia, los abogados cobran tarifas excesivas por papeleo simple, haciendo que el proceso sea inaccesible para muchos.",
    "opening_p2": "Creemos que todos merecen acceso a apoyo de inmigración asequible. Simplificamos el proceso de solicitud y aseguramos que sus formularios se completen con precisión y a tiempo. Con nuestra ayuda, puede manejar con confianza su documentación de inmigración sin un precio elevado, dándole tranquilidad y claridad en su camino hacia adelante.",
    "bp1": "Las tarifas más bajas",
    "bp2": "El servicio más rápido",
    "bp3": "Garantía de calidad",
    "services_heading": "Servicios",
    "basic": "Básico",
    "basic_txt": "Llenamos el formulario y le damos instrucciones sobre cómo enviarlo.",
    "premium": "Premium",
    "premium_txt": "¡Nos encargamos de todo! La tarifa de correo de primera clase está incluida en el precio.",
    "family": "Paquete familiar",
    "family_txt": "Todos los beneficios premium a un precio reducido si aplica para al menos 3 personas.",
    "translation": "Traducción",
    "translation_txt": "Traducciones certificadas de documentos oficiales como certificados de nacimiento, diplomas escolares, etc.",
    "translation_price": "15/página",
    "promo": "¡Valoramos sus recomendaciones! Una vez que haya adquirido nuestros servicios, ganará una comisión del 40% por cada recomendación exitosa. Las personas que usted recomiende también recibirán un descuento del 10% en su primera compra.",
    "faq_heading": "Preguntas frecuentes",
    "q1": "¿Quiénes somos?",
    "a1": "Somos un pequeño equipo de especialistas con experiencia de primera mano en el sistema de inmigración estadounidense, lo que nos permite comprender los desafíos que enfrentan la mayoría de los inmigrantes y la importancia de la accesibilidad, la precisión y la puntualidad en los asuntos de inmigración.",
    "q2": "¿Cómo funciona este proceso?",
    "a2": "Una vez que se comunique con nosotros a través del formulario a continuación, nos pondremos en contacto con usted dentro de las 12 horas para recopilar la información necesaria y responder cualquier otra pregunta que pueda tener, después de lo cual comenzaremos a trabajar en su solicitud.",
    "q3": "¿Qué pasa si la solicitud no es aceptada?",
    "a3": "¡Eso nunca ha sucedido! Pero si por alguna razón su solicitud es devuelta, la reintentaremos sin costo adicional para usted o simplemente le reembolsaremos el dinero, lo que prefiera.",
    "q4": "¿Ofrecen otros servicios?",
    "a4": "¡Sí! Ofrecemos diferentes tipos de servicios para inmigrantes con barreras lingüísticas y aquellos que necesitan ayuda para navegar diferentes tipos de sistemas en los EE. UU., como atención médica, banca, educación, etc.",
    "reviews_heading": "Reseñas",
    "contact_heading": "Contáctenos",
    "fname": "Nombre",
    "lname": "Apellido",
    "email": "Correo electrónico",
    "service": "Servicio",
    "ref_num": "Número de referencia (ponga 0 si no tiene)",
    "service_num": "Número de servicio",
    "service_num_incorrect": "El número de servicio es incorrecto",
    "choose_service": "Elija un servicio",
    "submit": "Enviar",
    "sent": "¡Gracias por su mensaje! Nos pondremos en contacto con usted pronto.",
    "error": "Hubo un error inesperado, intente nuevamente más tarde."
},
"fr": {
    "opening_heading": "Des services rapides et fiables aux meilleurs prix sur Internet !",
    "opening_p1": "Remplir des formulaires d'immigration n'a pas besoin d'être compliqué ou coûteux. Trop souvent, les avocats facturent des honoraires excessifs pour des formalités simples, rendant le processus inaccessible pour beaucoup.",
    "opening_p2": "Nous croyons que tout le monde mérite un accès à un soutien en immigration abordable. Nous simplifions le processus de candidature et veillons à ce que vos formulaires soient remplis avec précision et à temps. Avec notre aide, vous pouvez gérer vos documents d'immigration en toute confiance sans payer un prix exorbitant, vous offrant ainsi sérénité et clarté dans votre avenir.",
    "bp1": "Les prix les plus bas",
    "bp2": "Le service le plus rapide",
    "bp3": "Garantie de qualité",
    "services_heading": "Services",
    "basic": "Basique",
    "basic_txt": "Nous remplissons le formulaire et vous fournissons les instructions pour l'envoyer.",
    "premium": "Premium",
    "premium_txt": "Nous nous occupons de tout ! Les frais d'envoi en première classe sont inclus dans le prix.",
    "family": "Pack familial",
    "family_txt": "Tous les avantages Premium à un prix réduit si vous postulez pour au moins 3 personnes.",
    "translation": "Traduction",
    "translation_txt": "Traductions certifiées de documents officiels tels que certificats de naissance, diplômes, etc.",
    "translation_price": "15/page",
    "promo": "Nous apprécions vos recommandations ! Une fois que vous aurez acheté nos services, vous gagnerez une commission de 40 % pour chaque recommandation réussie. Les personnes que vous recommandez recevront également une réduction de 10 % sur leur premier achat.",
    "faq_heading": "FAQ",
    "q1": "Qui sommes-nous ?",
    "a1": "Nous sommes une petite équipe de spécialistes ayant une expérience directe du système d’immigration américain, c’est pourquoi nous comprenons les défis auxquels sont confrontés la plupart des immigrants et l’importance de l'accessibilité, de la précision et de la ponctualité dans les démarches d'immigration.",
    "q2": "Comment fonctionne ce processus ?",
    "a2": "Une fois que vous nous contactez via le formulaire ci-dessous, nous vous contacterons sous 12 heures pour collecter les informations nécessaires et répondre à vos questions, après quoi nous commencerons à travailler sur votre demande.",
    "q3": "Que se passe-t-il si la demande n'est pas acceptée ?",
    "a3": "Cela n'est jamais arrivé ! Mais si, pour une raison quelconque, votre demande est retournée, nous réessayerons sans frais supplémentaires pour vous ou vous rembourserons, selon votre préférence.",
    "q4": "Offrez-vous d'autres services ?",
    "a4": "Oui ! Nous proposons différents types de services pour les immigrants rencontrant des barrières linguistiques ou ayant besoin d'aide pour naviguer dans les systèmes de santé, bancaires, éducatifs, etc., aux États-Unis.",
    "reviews_heading": "Avis",
    "contact_heading": "Contactez-nous",
    "fname": "Prénom",
    "lname": "Nom de famille",
    "email": "E-mail",
    "service": "Service",
    "ref_num": "Numéro de référence (mettez 0 si vous n'en avez pas)",
    "choose_service": "Choisissez un service",
    "submit": "Soumettre",
    "service_num": "Numéro de service",
    "service_num_incorrect": "Le numéro de service est incorrect",
    "sent": "Merci pour votre message ! Nous vous contacterons bientôt.",
    "error": "Une erreur inattendue s'est produite. Veuillez réessayer plus tard."
},
"fa": {
    "opening_heading": "خدمات سریع و قابل اعتماد با بهترین قیمت‌ها در اینترنت!",
    "opening_p1": "تکمیل فرم‌های مهاجرت نباید پیچیده یا گران باشد. اغلب، وکلا برای انجام کاغذبازی ساده هزینه‌های گزافی می‌گیرند و این روند را برای بسیاری دست‌نیافتنی می‌کنند.",
    "opening_p2": "ما باور داریم که همه شایسته دسترسی به پشتیبانی مهاجرتی مقرون‌به‌صرفه هستند. ما روند درخواست را ساده کرده و اطمینان می‌دهیم که فرم‌های شما به‌درستی و به‌موقع تکمیل می‌شوند. با کمک ما، می‌توانید با اطمینان مدارک مهاجرت خود را بدون هزینه‌های سنگین مدیریت کنید و آرامش و وضوحی در مسیر آینده خود به دست آورید.",
    "bp1": "پایین‌ترین قیمت‌ها",
    "bp2": "سریع‌ترین خدمات",
    "bp3": "تضمین کیفیت",
    "services_heading": "خدمات",
    "basic": "پایه",
    "basic_txt": "ما فرم را پر می‌کنیم و دستورالعمل‌های ارسال را ارائه می‌دهیم.",
    "premium": "پریمیوم",
    "premium_txt": "ما همه‌چیز را مدیریت می‌کنیم! هزینه ارسال پست کلاس اول در قیمت گنجانده شده است.",
    "family": "بسته خانوادگی",
    "family_txt": "تمام مزایای پریمیوم با قیمت تخفیفی اگر برای حداقل ۳ نفر درخواست دهید.",
    "translation": "ترجمه",
    "translation_txt": "ترجمه‌های رسمی مدارکی مانند گواهی تولد، دیپلم‌های تحصیلی و غیره.",
    "translation_price": "15/صفحه",
    "promo": "ما به معرفی‌های شما ارزش می‌دهیم! پس از خرید خدمات ما، به ازای هر معرفی موفق ۴۰٪ کمیسیون دریافت می‌کنید. افرادی که معرفی می‌کنید نیز ۱۰٪ تخفیف برای اولین خرید خود دریافت خواهند کرد.",
    "faq_heading": "سؤالات متداول",
    "q1": "ما کی هستیم؟",
    "a1": "ما تیم کوچکی از متخصصان با تجربه مستقیم در سیستم مهاجرتی ایالات متحده هستیم که چالش‌های مهاجران و اهمیت دسترسی، دقت و به‌موقع بودن در امور مهاجرتی را درک می‌کنیم.",
    "q2": "این فرایند چگونه کار می‌کند؟",
    "a2": "پس از تماس شما از طریق فرم زیر، در عرض ۱۲ ساعت با شما تماس خواهیم گرفت تا اطلاعات لازم را جمع‌آوری کرده و به سؤالات شما پاسخ دهیم، سپس کار روی درخواست شما را شروع می‌کنیم.",
    "q3": "اگر درخواست پذیرفته نشود چه می‌شود؟",
    "a3": "این اتفاق هرگز نیفتاده است! اما اگر به هر دلیلی درخواست شما بازگردانده شود، بدون هزینه اضافی دوباره تلاش خواهیم کرد یا پول شما را بازپرداخت می‌کنیم، هر کدام که ترجیح می‌دهید.",
    "q4": "آیا خدمات دیگری ارائه می‌دهید؟",
    "a4": "بله! ما خدمات متنوعی را برای مهاجرانی که با موانع زبانی مواجه هستند یا به کمک برای استفاده از سیستم‌های مختلف مانند خدمات درمانی، بانکی و آموزشی در ایالات متحده نیاز دارند، ارائه می‌دهیم.",
    "reviews_heading": "نظرات",
    "contact_heading": "تماس با ما",
    "fname": "نام",
    "lname": "نام خانوادگی",
    "email": "ایمیل",
    "service": "خدمت",
    "ref_num": "شماره مرجع (در صورت نداشتن، ۰ بنویسید)",
    "service_num": "شماره خدمت",
    "service_num_incorrect": "شماره خدمت نادرست است",
    "choose_service": "یک خدمت انتخاب کنید",
    "submit": "ارسال",
    "sent": "از پیام شما متشکریم! به زودی با شما تماس خواهیم گرفت.",
    "error": "خطای غیرمنتظره‌ای رخ داد، لطفاً بعداً دوباره تلاش کنید."
},
"ar": {
    "opening_heading": "خدمات سريعة وموثوقة بأفضل الأسعار على الإنترنت!",
    "opening_p1": "ملء استمارات الهجرة لا يجب أن يكون معقدًا أو مكلفًا. غالبًا ما يفرض المحامون رسومًا باهظة على إجراءات بسيطة، مما يجعل العملية غير متاحة للكثيرين.",
    "opening_p2": "نؤمن بأن الجميع يستحقون الحصول على دعم للهجرة بتكلفة ميسورة. نبسط عملية التقديم ونتأكد من إكمال استماراتك بدقة وفي الوقت المناسب. بمساعدتنا، يمكنك التعامل مع وثائق الهجرة الخاصة بك بثقة وبدون تكلفة باهظة، مما يمنحك راحة البال والوضوح للمضي قدمًا.",
    "bp1": "أسعار أقل",
    "bp2": "خدمة سريعة",
    "bp3": "ضمان الجودة",
    "services_heading": "الخدمات",
    "basic": "أساسي",
    "basic_txt": "نملأ النموذج ونقدم تعليمات الإرسال.",
    "premium": "بريميوم",
    "premium_txt": "نتولى كل شيء! رسوم البريد من الدرجة الأولى مشمولة في السعر.",
    "family": "حزمة العائلة",
    "family_txt": "جميع مزايا البريميوم بسعر مخفض عند التقديم لثلاثة أشخاص على الأقل.",
    "translation": "ترجمة",
    "translation_txt": "ترجمات معتمدة لوثائق رسمية مثل شهادات الميلاد، الدبلومات المدرسية، إلخ.",
    "translation_price": "15/صفحة",
    "promo": "نقدر توصياتك! بعد شراء خدماتنا، ستحصل على عمولة بنسبة 40٪ عن كل توصية ناجحة. الأشخاص الذين يتم توصيتهم سيحصلون أيضًا على خصم بنسبة 10٪ على أول عملية شراء لهم.",
    "faq_heading": "الأسئلة الشائعة",
    "q1": "من نحن؟",
    "a1": "نحن فريق صغير من المتخصصين ذوي الخبرة المباشرة في نظام الهجرة الأمريكي، نفهم التحديات التي يواجهها معظم المهاجرين وأهمية الحصول على خدمات دقيقة وفي الوقت المناسب.",
    "q2": "كيف يتم تنفيذ الخدمات المطروحة؟",
    "a2": "بمجرد التواصل معنا عبر النموذج أدناه، سنتصل بك خلال 12 ساعة لجمع المعلومات اللازمة والإجابة على أسئلتك، وبعد ذلك سنبدأ العمل على طلبك.",
    "q3": "ماذا يحدث إذا لم يتم قبول الطلب؟",
    "a3": "هذا لم يحدث أبدًا! ولكن إذا تم رفض طلبك لأي سبب، فسنحاول مرة أخرى دون أي تكلفة إضافية، أو سنعيد المبلغ إليك حسب تفضيلك.",
    "q4": "هل تقدمون خدمات أخرى؟",
    "a4": "نعم! نقدم خدمات متنوعة للمهاجرين الذين يواجهون حواجز لغوية أو يحتاجون إلى مساعدة في التعامل مع أنظمة مثل الرعاية الصحية، البنوك، التعليم، وغيرها في الولايات المتحدة.",
    "reviews_heading": "التقييمات",
    "contact_heading": "اتصل بنا",
    "fname": "الاسم الأول",
    "lname": "اسم العائلة",
    "email": "البريد الإلكتروني",
    "service": "الخدمة",
    "ref_num": "رقم المرجع (اكتب 0 إذا لم يكن لديك)",
    "service_num": "رقم الخدمة",
    "service_num_incorrect": "رقم الخدمة غير صحيح",
    "choose_service": "اختر الخدمة",
    "submit": "إرسال",
    "sent": "شكرًا لرسالتك! سنتواصل معك قريبًا.",
    "error": "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى لاحقًا."
}
    }
    
    return langObj[lang][location]
} 

export const PlaceholderProvider = ({ lang, location }) => {

    const langObj = {
        "en": {
            "msg": "Brief message",
            "review": "Review"
        },
        "ru": {
            "msg": "Краткое сообщение",
            "review": "Отзыв"
        },
        "tr": {
            "msg": "Kısa mesaj",
            "review": "Yorum"
        },
        "ar": {
            "msg": "رسالة قصيرة",
            "review": "مراجعة"
        },
        "fr": {
            "msg": "Message bref",
            "review": "Avis"
        },
        "es": {
            "msg": "Mensaje breve",
            "review": "Reseña"
        },
        "fa": {
            "msg": "پیام کوتاه",
            "review": "بازخورد"
        }
    }

    return langObj[lang][location]
}